"""SDK codegen - deterministic file writer.

Public API:
    generate(forge_dir, target, out_dir) -> dict
        Writes the SDK files into out_dir. Returns {"files": [...]}
        listing the produced paths + their sha256.

The agent calls generate("typescript", "./src/forge-sdk") inside its
RARV iteration; the user-app's import paths come up working in the
next iteration.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import time
from typing import Any, Dict, List, Optional


class GenError(Exception):
    pass


SUPPORTED_TARGETS = ("typescript", "python", "kotlin", "swift", "go")


# Type maps from forge migration aliases -> language native types.
_TS_TYPES = {
    "id": "number",
    "integer": "number",
    "real": "number",
    "boolean": "boolean",
    "text": "string",
    "uuid": "string",
    "timestamp": "string",
    "json": "any",
    "blob": "ArrayBuffer",
}

_PY_TYPES = {
    "id": "int",
    "integer": "int",
    "real": "float",
    "boolean": "bool",
    "text": "str",
    "uuid": "str",
    "timestamp": "str",
    "json": "Any",
    "blob": "bytes",
}


def list_targets() -> List[str]:
    return list(SUPPORTED_TARGETS)


def _state_dump(forge_dir: str) -> Dict[str, Any]:
    """Pull live state. Mirrors forge_state_dump MCP tool."""
    state: Dict[str, Any] = {}
    try:
        from forge.services.database import open_engine, introspect
        if os.path.exists(os.path.join(forge_dir, "db.sqlite")):
            state["database"] = introspect(open_engine(forge_dir))
    except Exception as e:
        state["database_error"] = str(e)
    try:
        from forge.services.storage import list_buckets
        state["buckets"] = list_buckets(forge_dir)
    except Exception:
        state["buckets"] = []
    try:
        from forge.services.functions import list_functions
        state["functions"] = list_functions(forge_dir)
    except Exception:
        state["functions"] = []
    try:
        from forge.services.auth import list_providers
        state["auth_providers"] = list_providers(forge_dir)
    except Exception:
        state["auth_providers"] = []
    try:
        from forge.services.realtime import list_channels
        state["channels"] = list_channels(forge_dir)
    except Exception:
        state["channels"] = []
    return state


def generate(forge_dir: str, target: str,
             out_dir: str,
             base_url: str = "/forge") -> Dict[str, Any]:
    if target not in SUPPORTED_TARGETS:
        raise GenError(f"unsupported target: {target!r}; "
                       f"choose from {list(SUPPORTED_TARGETS)}")
    if not isinstance(out_dir, str) or not out_dir:
        raise GenError("out_dir required")
    os.makedirs(out_dir, exist_ok=True)
    state = _state_dump(forge_dir)
    if target == "typescript":
        written = _gen_typescript(state, out_dir, base_url)
    elif target == "python":
        written = _gen_python(state, out_dir, base_url)
    elif target == "kotlin":
        written = _gen_kotlin(state, out_dir, base_url)
    elif target == "swift":
        written = _gen_swift(state, out_dir, base_url)
    elif target == "go":
        written = _gen_go(state, out_dir, base_url)
    else:
        raise GenError(f"target not implemented: {target}")

    # Pin the (target, out_dir) so X-18 auto-regen kicks in on the next
    # forge_db_migrate apply.
    try:
        pin_dir = os.path.join(forge_dir, "sdk")
        os.makedirs(pin_dir, exist_ok=True)
        pin = {
            "target": target,
            "out_dir": os.path.abspath(out_dir),
            "base_url": base_url,
            "generated_at": int(time.time()),
        }
        tmp = os.path.join(pin_dir, ".last_target.json.tmp")
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(pin, f, indent=2, sort_keys=True)
        os.replace(tmp, os.path.join(pin_dir, ".last_target.json"))
    except Exception:
        pass

    return {
        "schema": "loki.forge.sdk.generate/v1",
        "target": target,
        "out_dir": os.path.abspath(out_dir),
        "files": written,
        "generated_at": int(time.time()),
    }


# ---- TypeScript -----------------------------------------------------------


def _gen_typescript(state: Dict[str, Any], out_dir: str,
                    base_url: str) -> List[Dict[str, Any]]:
    files: List[Dict[str, Any]] = []

    # types.ts: row interfaces per table.
    parts: List[str] = ["// Auto-generated by forge.sdk - do not edit",
                        "// Regenerate via: forge_sdk_generate", ""]
    for t in (state.get("database") or {}).get("tables", []):
        parts.append(f"export interface {_pascal(t['name'])} {{")
        for c in t["columns"]:
            ts_type = _TS_TYPES.get(_norm_type(c.get("type", "text")), "string")
            opt = "?" if not (c.get("notnull") or c.get("primary_key")) else ""
            parts.append(f"  {c['name']}{opt}: {ts_type};")
        parts.append("}")
        parts.append("")
    files.append(_write(out_dir, "types.ts", "\n".join(parts)))

    # client.ts: a fetch-based client with table/bucket/function/realtime helpers.
    client_parts: List[str] = [
        "// Auto-generated by forge.sdk - do not edit",
        "import type * as T from \"./types\";",
        "",
        "export interface ForgeOptions {",
        "  baseUrl?: string;",
        "  token?: string | (() => string | Promise<string>);",
        "  fetch?: typeof fetch;",
        "}",
        "",
        "export class ForgeClient {",
        "  private baseUrl: string;",
        "  private token?: ForgeOptions[\"token\"];",
        "  private fetchImpl: typeof fetch;",
        "  constructor(opts: ForgeOptions = {}) {",
        f"    this.baseUrl = (opts.baseUrl ?? {json.dumps(base_url)}).replace(/\\/$/, \"\");",
        "    this.token = opts.token;",
        "    this.fetchImpl = opts.fetch ?? globalThis.fetch;",
        "  }",
        "",
        "  private async authHeader(): Promise<Record<string, string>> {",
        "    if (!this.token) return {};",
        "    const v = typeof this.token === \"function\" ? await this.token() : this.token;",
        "    return v ? { Authorization: `Bearer ${v}` } : {};",
        "  }",
        "",
        "  async request<R = unknown>(method: string, path: string, body?: unknown): Promise<R> {",
        "    const headers: Record<string, string> = { ...(await this.authHeader()) };",
        "    if (body !== undefined) headers[\"Content-Type\"] = \"application/json\";",
        "    const res = await this.fetchImpl(this.baseUrl + path, {",
        "      method,",
        "      headers,",
        "      body: body === undefined ? undefined : JSON.stringify(body),",
        "    });",
        "    if (!res.ok) {",
        "      const text = await res.text().catch(() => \"\");",
        "      throw new Error(`forge ${method} ${path} -> ${res.status} ${text}`);",
        "    }",
        "    return res.json() as Promise<R>;",
        "  }",
        "",
        "  // -- typed table accessors ----------------------------------",
    ]
    for t in (state.get("database") or {}).get("tables", []):
        name = t["name"]
        pascal = _pascal(name)
        client_parts.append(f"  {name} = {{")
        client_parts.append(
            f"    list: () => this.request<T.{pascal}[]>(\"GET\", \"/db/v1/{name}\"),"
        )
        client_parts.append(
            f"    get: (id: string | number) => "
            f"this.request<T.{pascal}>(\"GET\", `/db/v1/{name}/${{id}}`),"
        )
        client_parts.append(
            f"    insert: (row: Partial<T.{pascal}>) => "
            f"this.request<T.{pascal}>(\"POST\", \"/db/v1/{name}\", row),"
        )
        client_parts.append("  };")

    # Buckets.
    for b in state.get("buckets", []) or []:
        bname = b["name"]
        safe = _safe_id(bname)
        client_parts.append(
            f"  storage_{safe} = {{"
        )
        client_parts.append(
            f"    signedUrl: (path: string, expiresIn = 3600) => "
            f"this.request<{{url: string}}>(\"POST\", "
            f"\"/storage/v1/{bname}/sign\", {{ path, expiresIn }}),"
        )
        client_parts.append("  };")

    # Functions.
    for fn in state.get("functions", []) or []:
        fname = fn["name"]
        safe = _safe_id(fname)
        client_parts.append(
            f"  fn_{safe} = (payload?: unknown) => "
            f"this.request<{{ok:boolean; stdout:string; stderr:string}}>"
            f"(\"POST\", \"/functions/v1/{fname}\", payload);"
        )

    # Realtime channels.
    if state.get("channels"):
        client_parts.append("")
        client_parts.append("  /** Open a WebSocket to a realtime channel. */")
        client_parts.append(
            "  subscribe(channel: string, onMessage: (msg: unknown) => void): WebSocket {"
        )
        client_parts.append(
            "    const ws = new WebSocket(this.baseUrl.replace(/^http/, \"ws\") + "
            "`/realtime/v1?channel=${encodeURIComponent(channel)}`);"
        )
        client_parts.append("    ws.onmessage = (ev) => onMessage(JSON.parse(ev.data));")
        client_parts.append("    return ws;")
        client_parts.append("  }")
    client_parts.append("}")
    client_parts.append("")
    client_parts.append("export function createForge(opts?: ForgeOptions) {")
    client_parts.append("  return new ForgeClient(opts);")
    client_parts.append("}")
    files.append(_write(out_dir, "client.ts", "\n".join(client_parts)))

    # index.ts re-exports.
    files.append(_write(out_dir, "index.ts",
                        "export * from \"./client\";\nexport * from \"./types\";\n"))

    # package.json scaffold.
    pkg = {
        "name": "@loki/forge-sdk",
        "version": "0.1.0",
        "type": "module",
        "main": "index.ts",
        "exports": {".": "./index.ts"},
    }
    files.append(_write(out_dir, "package.json",
                        json.dumps(pkg, indent=2, sort_keys=True) + "\n"))
    return files


# ---- Python ---------------------------------------------------------------


def _gen_python(state: Dict[str, Any], out_dir: str,
                base_url: str) -> List[Dict[str, Any]]:
    files: List[Dict[str, Any]] = []

    parts: List[str] = [
        '"""Auto-generated by forge.sdk - do not edit"""',
        "from __future__ import annotations",
        "from dataclasses import dataclass",
        "from typing import Any, List, Optional",
        "",
    ]
    for t in (state.get("database") or {}).get("tables", []):
        parts.append("@dataclass")
        parts.append(f"class {_pascal(t['name'])}:")
        # Required (notnull/pk) fields first; optional ones with defaults
        # after - dataclasses cannot have non-default after default fields.
        required: List[Any] = []
        optional: List[Any] = []
        for c in t["columns"]:
            py_base = _PY_TYPES.get(_norm_type(c.get("type", "text")), "str")
            if c.get("notnull") or c.get("primary_key"):
                required.append((c["name"], py_base))
            else:
                optional.append((c["name"], f"Optional[{py_base}] = None"))
        emitted = False
        for nm, ann in required + optional:
            parts.append(f"    {nm}: {ann}")
            emitted = True
        if not emitted:
            parts.append("    pass")
        parts.append("")
    files.append(_write(out_dir, "types.py", "\n".join(parts)))

    client_parts: List[str] = [
        '"""Auto-generated by forge.sdk client - do not edit"""',
        "from __future__ import annotations",
        "import json",
        "from typing import Any, Awaitable, Callable, Dict, Optional, Union",
        "from . import types as T",
        "",
        "class ForgeError(Exception):",
        "    pass",
        "",
        "class ForgeClient:",
        f"    def __init__(self, base_url: str = {json.dumps(base_url)},",
        "                 token: Optional[Union[str, Callable[[], str]]] = None,",
        "                 transport: Optional[Any] = None):",
        "        self.base_url = base_url.rstrip('/')",
        "        self.token = token",
        "        self._http = transport",
        "",
        "    def _client(self):",
        "        if self._http is not None:",
        "            return self._http",
        "        try:",
        "            import httpx",
        "        except ImportError as e:",
        "            raise ForgeError('install httpx for the default transport') from e",
        "        return httpx.Client(base_url=self.base_url)",
        "",
        "    def _auth_header(self) -> Dict[str, str]:",
        "        if not self.token:",
        "            return {}",
        "        v = self.token() if callable(self.token) else self.token",
        "        return {'Authorization': f'Bearer {v}'} if v else {}",
        "",
        "    def request(self, method: str, path: str, body: Any = None) -> Any:",
        "        client = self._client()",
        "        headers = {'Content-Type': 'application/json'} if body is not None else {}",
        "        headers.update(self._auth_header())",
        "        resp = client.request(method, path, headers=headers,",
        "                              content=None if body is None else json.dumps(body).encode())",
        "        if resp.status_code // 100 != 2:",
        "            raise ForgeError(f'{method} {path} -> {resp.status_code}: {resp.text[:200]}')",
        "        return resp.json()",
        "",
    ]
    for t in (state.get("database") or {}).get("tables", []):
        name = t["name"]
        client_parts.append(f"    def {name}_list(self):")
        client_parts.append(f"        return self.request('GET', '/db/v1/{name}')")
        client_parts.append(f"    def {name}_get(self, id):")
        client_parts.append(f"        return self.request('GET', f'/db/v1/{name}/{{id}}')")
        client_parts.append(f"    def {name}_insert(self, row):")
        client_parts.append(f"        return self.request('POST', '/db/v1/{name}', row)")
        client_parts.append("")

    for b in state.get("buckets", []) or []:
        bname = b["name"]
        safe = _safe_id(bname)
        client_parts.append(
            f"    def storage_{safe}_signed_url(self, path: str, expires_in: int = 3600):"
        )
        client_parts.append(
            f"        return self.request('POST', '/storage/v1/{bname}/sign', "
            f"{{'path': path, 'expiresIn': expires_in}})"
        )
        client_parts.append("")

    for fn in state.get("functions", []) or []:
        fname = fn["name"]
        safe = _safe_id(fname)
        client_parts.append(
            f"    def fn_{safe}(self, payload: Any = None):"
        )
        client_parts.append(
            f"        return self.request('POST', '/functions/v1/{fname}', payload)"
        )
        client_parts.append("")

    files.append(_write(out_dir, "client.py", "\n".join(client_parts)))

    files.append(_write(out_dir, "__init__.py",
                        '"""forge-sdk (auto-generated)"""\n'
                        "from .client import ForgeClient, ForgeError  # noqa: F401\n"
                        "from . import types  # noqa: F401\n"))
    return files


# ---- Kotlin --------------------------------------------------------------

_KT_TYPES = {
    "id": "Long",
    "integer": "Long",
    "real": "Double",
    "boolean": "Boolean",
    "text": "String",
    "uuid": "String",
    "timestamp": "String",
    "json": "Any",
    "blob": "ByteArray",
}


def _gen_kotlin(state: Dict[str, Any], out_dir: str,
                base_url: str) -> List[Dict[str, Any]]:
    files: List[Dict[str, Any]] = []
    parts: List[str] = [
        "// Auto-generated by forge.sdk - do not edit",
        "package loki.forge",
        "",
    ]
    for t in (state.get("database") or {}).get("tables", []):
        parts.append(f"data class {_pascal(t['name'])}(")
        cols = []
        # Required first, optional with default after (Kotlin doesn't
        # require this but it matches Python's rule and improves
        # constructor ergonomics).
        required = []
        optional = []
        for c in t["columns"]:
            kt_type = _KT_TYPES.get(_norm_type(c.get("type", "text")), "String")
            if c.get("notnull") or c.get("primary_key"):
                required.append((c["name"], kt_type))
            else:
                optional.append((c["name"], f"{kt_type}? = null"))
        for nm, ann in required:
            cols.append(f"    val {nm}: {ann}")
        for nm, ann in optional:
            cols.append(f"    val {nm}: {ann}")
        parts.append(",\n".join(cols))
        parts.append(")")
        parts.append("")
    files.append(_write(out_dir, "Types.kt", "\n".join(parts)))

    client = [
        "// Auto-generated by forge.sdk - do not edit",
        "package loki.forge",
        "",
        "class ForgeClient(",
        f"    private val baseUrl: String = {json.dumps(base_url)},",
        "    private val token: (() -> String?)? = null,",
        ") {",
        "    // Use Ktor / OkHttp / java.net.http on the consumer side.",
        "    // This stub provides the URL builder + auth header logic;",
        "    // the actual HTTP client is injected by the user app.",
        "    fun authHeader(): Map<String, String> =",
        "        token?.invoke()?.let { mapOf(\"Authorization\" to \"Bearer $it\") } ?: emptyMap()",
        "    fun urlFor(path: String): String = \"${baseUrl.trimEnd('/')}$path\"",
        "}",
        "",
    ]
    files.append(_write(out_dir, "ForgeClient.kt", "\n".join(client)))
    return files


# ---- Swift ---------------------------------------------------------------

_SW_TYPES = {
    "id": "Int64",
    "integer": "Int64",
    "real": "Double",
    "boolean": "Bool",
    "text": "String",
    "uuid": "String",
    "timestamp": "String",
    "json": "Any",
    "blob": "Data",
}


def _gen_swift(state: Dict[str, Any], out_dir: str,
               base_url: str) -> List[Dict[str, Any]]:
    files: List[Dict[str, Any]] = []
    parts: List[str] = [
        "// Auto-generated by forge.sdk - do not edit",
        "import Foundation",
        "",
    ]
    for t in (state.get("database") or {}).get("tables", []):
        parts.append(f"public struct {_pascal(t['name'])}: Codable {{")
        for c in t["columns"]:
            sw_type = _SW_TYPES.get(_norm_type(c.get("type", "text")), "String")
            opt = "" if (c.get("notnull") or c.get("primary_key")) else "?"
            parts.append(f"    public let {c['name']}: {sw_type}{opt}")
        parts.append("}")
        parts.append("")
    files.append(_write(out_dir, "Types.swift", "\n".join(parts)))

    client = [
        "// Auto-generated by forge.sdk - do not edit",
        "import Foundation",
        "",
        "public struct ForgeClient {",
        f"    public let baseURL: URL",
        "    public let token: (() -> String?)?",
        "    public init(baseURL: URL? = nil, token: (() -> String?)? = nil) {",
        f"        self.baseURL = baseURL ?? URL(string: {json.dumps(base_url)})!",
        "        self.token = token",
        "    }",
        "    public func url(for path: String) -> URL {",
        "        baseURL.appendingPathComponent(path)",
        "    }",
        "}",
        "",
    ]
    files.append(_write(out_dir, "ForgeClient.swift", "\n".join(client)))
    return files


# ---- Go ------------------------------------------------------------------

_GO_TYPES = {
    "id": "int64",
    "integer": "int64",
    "real": "float64",
    "boolean": "bool",
    "text": "string",
    "uuid": "string",
    "timestamp": "string",
    "json": "interface{}",
    "blob": "[]byte",
}


def _gen_go(state: Dict[str, Any], out_dir: str,
            base_url: str) -> List[Dict[str, Any]]:
    files: List[Dict[str, Any]] = []
    parts: List[str] = [
        "// Auto-generated by forge.sdk - do not edit",
        "package forge",
        "",
    ]
    for t in (state.get("database") or {}).get("tables", []):
        parts.append(f"type {_pascal(t['name'])} struct {{")
        for c in t["columns"]:
            go_type = _GO_TYPES.get(_norm_type(c.get("type", "text")), "string")
            field_name = _pascal(c["name"])
            json_tag = c["name"]
            if not (c.get("notnull") or c.get("primary_key")):
                # nil-able via pointer
                go_type = "*" + go_type if not go_type.startswith("*") else go_type
            parts.append(f"\t{field_name} {go_type} `json:\"{json_tag}\"`")
        parts.append("}")
        parts.append("")
    files.append(_write(out_dir, "types.go", "\n".join(parts)))

    client = [
        "// Auto-generated by forge.sdk - do not edit",
        "package forge",
        "",
        "import \"net/http\"",
        "",
        "type Client struct {",
        "\tBaseURL string",
        "\tToken   string",
        "\tHTTP    *http.Client",
        "}",
        "",
        f"const DefaultBaseURL = {json.dumps(base_url)}",
        "",
        "func NewClient(baseURL, token string) *Client {",
        "\tif baseURL == \"\" {",
        "\t\tbaseURL = DefaultBaseURL",
        "\t}",
        "\treturn &Client{BaseURL: baseURL, Token: token, HTTP: http.DefaultClient}",
        "}",
        "",
    ]
    files.append(_write(out_dir, "client.go", "\n".join(client)))
    return files


# ---- helpers --------------------------------------------------------------


def _write(out_dir: str, name: str, content: str) -> Dict[str, Any]:
    path = os.path.join(out_dir, name)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(tmp, path)
    sha = hashlib.sha256(content.encode("utf-8")).hexdigest()
    return {"path": path, "sha256": sha, "bytes": len(content)}


def _pascal(s: str) -> str:
    parts = re.split(r"[_\-]+", s)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def _norm_type(t: str) -> str:
    """Normalize a SQL column type to a forge alias for the type-map lookup."""
    if not isinstance(t, str):
        return "text"
    t = t.lower().split("(", 1)[0].strip()
    # Map common SQL types to our alias namespace.
    if t in ("varchar", "char", "citext"):
        return "text"
    if t in ("bigint", "smallint", "int2", "int4", "int8", "int"):
        return "integer"
    if t in ("double", "float4", "float8", "numeric"):
        return "real"
    if t in ("bool",):
        return "boolean"
    if t in ("jsonb",):
        return "json"
    if t in ("timestamptz", "datetime", "date"):
        return "timestamp"
    if t == "bytea":
        return "blob"
    return t


def _safe_id(s: str) -> str:
    """Sanitize identifiers used in client method names."""
    out = re.sub(r"[^A-Za-z0-9_]", "_", s)
    if out and out[0].isdigit():
        out = "_" + out
    return out
